export const labels = [
  { name: 'Web Development and Hosting' },
  { name: 'Customer Relationship Management (CRM)' },
  { name: 'Project Management and Collaboration' },
  { name: 'Human Resources (HR) and Employee Management' },
  { name: 'Financial Technology (FinTech)' },
  { name: 'E-commerce and Retail' },
  { name: 'Healthcare Technology (HealthTech)' },
  { name: 'Educational Technology (EdTech)' },
  { name: 'Marketing Automation' },
  { name: 'Analytics and Business Intelligence' },
  { name: 'Cybersecurity' },
  { name: 'Real Estate Technology (PropTech)' },
  { name: 'Legal Technology (LegalTech)' },
  { name: 'Supply Chain Management' },
  { name: 'Web3 and Blockchain' },
  { name: 'Artificial Intelligence (AI) and Machine Learning (ML)' },
  { name: 'IoT (Internet of Things)' },
  { name: 'Communication and Collaboration' },
  { name: 'Travel and Hospitality' },
  { name: 'Environmental, Social, and Governance (ESG) Tech' },
];
